fluentd:
  enabled: true 
fluentd-tester:
  enabled: true 
log-aggregator:
  enabled: true 
  flexVolumeDir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
global:
  systemDefaultRegistry: "k8s.io"
